import { Metadata } from "next";
import Image from "next/image";
import perf from "./components/photos/perf.avif";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home(): JSX.Element {
  return (
    <div className="h-screen flex justify-center items-center ">
      <div className="w-full max-w-screen-xl">
        <div>
          <Image
            src={perf}
            alt="makeup"
            // layout="fill"
            objectFit="cover"
            className="h-[500px] sm:h-[600px] lg:h-[700px] xl:h-[800px] 2xl:h-[900px]"
          />

        </div>
        <button className="bg-[#CEFF00] text-slate-800 font-bold uppercase text-1xl lg:text-[20px] px-4 py-2 rounded-full hover:bg-slate-800 hover:text-[#CEFF00] ease-in duration-300">
          SHOP NOW
        </button>
      </div>
    </div>
    // </div>
  );
}
